
package com.mtomfileupload;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileUploadMTOMService", targetNamespace = "MTOMfileupload.com", wsdlLocation = "http://localhost:8090/MTOM/MTOMfileUpload?wsdl")
public class FileUploadMTOMService
    extends Service
{

    private final static URL FILEUPLOADMTOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILEUPLOADMTOMSERVICE_EXCEPTION;
    private final static QName FILEUPLOADMTOMSERVICE_QNAME = new QName("MTOMfileupload.com", "FileUploadMTOMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/MTOM/MTOMfileUpload?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILEUPLOADMTOMSERVICE_WSDL_LOCATION = url;
        FILEUPLOADMTOMSERVICE_EXCEPTION = e;
    }

    public FileUploadMTOMService() {
        super(__getWsdlLocation(), FILEUPLOADMTOMSERVICE_QNAME);
    }

    public FileUploadMTOMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILEUPLOADMTOMSERVICE_QNAME, features);
    }

    public FileUploadMTOMService(URL wsdlLocation) {
        super(wsdlLocation, FILEUPLOADMTOMSERVICE_QNAME);
    }

    public FileUploadMTOMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILEUPLOADMTOMSERVICE_QNAME, features);
    }

    public FileUploadMTOMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileUploadMTOMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MTOMfileUploadService
     */
    @WebEndpoint(name = "MTOMfileuploadPort")
    public MTOMfileUploadService getMTOMfileuploadPort() {
        return super.getPort(new QName("MTOMfileupload.com", "MTOMfileuploadPort"), MTOMfileUploadService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MTOMfileUploadService
     */
    @WebEndpoint(name = "MTOMfileuploadPort")
    public MTOMfileUploadService getMTOMfileuploadPort(WebServiceFeature... features) {
        return super.getPort(new QName("MTOMfileupload.com", "MTOMfileuploadPort"), MTOMfileUploadService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILEUPLOADMTOMSERVICE_EXCEPTION!= null) {
            throw FILEUPLOADMTOMSERVICE_EXCEPTION;
        }
        return FILEUPLOADMTOMSERVICE_WSDL_LOCATION;
    }

}
