
package com.mtomfileupload;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTOMfileUploadService", targetNamespace = "MTOMfileupload.com")
@XmlSeeAlso({
    com.mtomfileupload.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface MTOMfileUploadService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadMTOMWay", targetNamespace = "MTOMfileupload.com", className = "com.mtomfileupload.UploadMTOMWay")
    @ResponseWrapper(localName = "uploadMTOMWayResponse", targetNamespace = "MTOMfileupload.com", className = "com.mtomfileupload.UploadMTOMWayResponse")
    @Action(input = "MTOMfileupload.com/MTOMfileUploadService/uploadMTOMWayRequest", output = "MTOMfileupload.com/MTOMfileUploadService/uploadMTOMWayResponse")
    public void uploadMTOMWay(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0);

}
