
package com.fileupload;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileUploadService", targetNamespace = "fileupload.com", wsdlLocation = "http://localhost:8090/MTOM/fileUpload?wsdl")
public class FileUploadService_Service
    extends Service
{

    private final static URL FILEUPLOADSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILEUPLOADSERVICE_EXCEPTION;
    private final static QName FILEUPLOADSERVICE_QNAME = new QName("fileupload.com", "FileUploadService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/MTOM/fileUpload?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILEUPLOADSERVICE_WSDL_LOCATION = url;
        FILEUPLOADSERVICE_EXCEPTION = e;
    }

    public FileUploadService_Service() {
        super(__getWsdlLocation(), FILEUPLOADSERVICE_QNAME);
    }

    public FileUploadService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILEUPLOADSERVICE_QNAME, features);
    }

    public FileUploadService_Service(URL wsdlLocation) {
        super(wsdlLocation, FILEUPLOADSERVICE_QNAME);
    }

    public FileUploadService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILEUPLOADSERVICE_QNAME, features);
    }

    public FileUploadService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileUploadService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileUploadService
     */
    @WebEndpoint(name = "fileuploadPort")
    public FileUploadService getFileuploadPort() {
        return super.getPort(new QName("fileupload.com", "fileuploadPort"), FileUploadService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileUploadService
     */
    @WebEndpoint(name = "fileuploadPort")
    public FileUploadService getFileuploadPort(WebServiceFeature... features) {
        return super.getPort(new QName("fileupload.com", "fileuploadPort"), FileUploadService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILEUPLOADSERVICE_EXCEPTION!= null) {
            throw FILEUPLOADSERVICE_EXCEPTION;
        }
        return FILEUPLOADSERVICE_WSDL_LOCATION;
    }

}
